---
- name: System Update
  hosts: all
  become: true
  tasks:
    - apt:
        update_cache: yes
        upgrade: dist

- name: Install nginx and docker
  hosts: all
  become: true
  tasks:
    - apt:
        name:
            - nginx
        state: present
        update_cache: yes

- name: nginx config and html index
  hosts: all
  become: true
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: azureuser
        state: present
        key: "{{ lookup('file', './files/azure.pub') }}"
    
    - name: copy config
      copy:
        src: files/proxy.config
        dest: /etc/nginx/sites-enabled/default

    - name: copy cgi config
      copy:
        src: files/cgi.config
        dest: /etc/nginx/sites-enabled/cgi

    - name: copy html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted

## firewall ufw
- name: firewall configuration
  hosts: all
  become: true
  tasks:
    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    - name: Allow all access to tcp port 80 
      community.general.ufw: 
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow all access to tcp port 443
      community.general.ufw: 
        rule: allow
        port: '443'
        proto: tcp

    - name: Allow all access to tcp port 22
      community.general.ufw: 
        rule: allow
        port: '22'
        proto: tcp